apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "expense-tracker.fullname" . }}
  labels:
    {{- include "expense-tracker.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  REDIS_SSL: {{ .Values.config.redisSsl | quote }}