apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "expense-tracker.fullname" . }}
  labels:
    {{- include "expense-tracker.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "expense-tracker.selectorLabels" . | nindent 6 }}
