apiVersion: v1
kind: Secret
metadata:
  name: {{ include "expense-tracker.fullname" . }}
  labels:
    {{- include "expense-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
