apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "expense-tracker.fullname" . }}
  labels:
    {{- include "expense-tracker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "expense-tracker.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
